"use client";

import { useEffect, useRef } from "react";
import { createPortal } from "react-dom";
import { Printer, X } from "lucide-react";
import { ReportHeader } from "@/components/reports/ReportHeader";
import { PRINT_STYLES } from "@/lib/reports/print-styles";
import { printReportDocument } from "@/lib/reports/print-document";

type PrintReportModalProps = {
  open: boolean;
  title: string;
  bodyHtml: string;
  autoPrint?: boolean;
  onClose: () => void;
};

export function PrintReportModal({
  open,
  title,
  bodyHtml,
  autoPrint = false,
  onClose,
}: PrintReportModalProps) {
  const contentRef = useRef<HTMLDivElement>(null);
  const printedRef = useRef(false);

  const handlePrint = () => {
    printReportDocument(title, bodyHtml);
  };

  useEffect(() => {
    if (!open) {
      printedRef.current = false;
      return;
    }
    if (!autoPrint || printedRef.current || !bodyHtml) return;

    const timer = window.setTimeout(() => {
      if (printedRef.current) return;
      printedRef.current = true;
      printReportDocument(title, bodyHtml);
    }, Math.min(1200, 300 + Math.floor(bodyHtml.length / 8000)));

    return () => window.clearTimeout(timer);
  }, [open, autoPrint, bodyHtml, title]);

  if (!open || typeof document === "undefined") return null;

  return createPortal(
    <>
      <style>{`
        ${PRINT_STYLES}
        #hwo-print-root {
          position: fixed;
          inset: 0;
          z-index: 9999;
          background: white;
          overflow: auto;
        }
        #hwo-print-root .hwo-print-toolbar {
          position: sticky;
          top: 0;
          z-index: 10;
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 12px;
          padding: 12px 20px;
          background: #f8fafc;
          border-bottom: 1px solid #e2e8f0;
        }
        #hwo-print-root .hwo-print-body {
          max-width: 900px;
          margin: 0 auto;
          padding: 24px;
          font-family: Arial, Helvetica, sans-serif;
          color: #1e293b;
        }
      `}</style>
      <div id="hwo-print-root" role="dialog" aria-label={title}>
        <div className="hwo-print-toolbar">
          <div>
            <p className="text-sm font-semibold text-slate-800">{title}</p>
            <p className="text-xs text-slate-500">
              Preparing print… or click Print / Save PDF below
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={handlePrint}
              className="flex items-center gap-2 rounded-lg bg-teal-500 px-4 py-2 text-sm font-medium text-white hover:bg-teal-600"
            >
              <Printer className="h-4 w-4" />
              Print / Save PDF
            </button>
            <button
              type="button"
              onClick={onClose}
              className="rounded-lg border border-slate-200 p-2 hover:bg-slate-100"
              aria-label="Close"
            >
              <X className="h-4 w-4" />
            </button>
          </div>
        </div>
        <div ref={contentRef} className="hwo-print-body">
          <ReportHeader />
          <div dangerouslySetInnerHTML={{ __html: bodyHtml }} />
          <div
            className="footer"
            style={{ marginTop: 24, fontSize: 10, color: "#94a3b8", textAlign: "center" }}
          >
            Generated by Health Workforce Optimizer · {new Date().toLocaleString()}
          </div>
        </div>
      </div>
    </>,
    document.body
  );
}
