import { PRINT_STYLES } from "@/lib/reports/print-styles";

export function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Plain text or pre-built HTML (e.g. risk badges). */
export function tableCell(value: string) {
  if (value.includes("<") && value.includes(">")) return value;
  return escapeHtml(value);
}

export function printReportDocument(
  title: string,
  bodyHtml: string,
  options?: { onDone?: () => void }
) {
  const origin = typeof window !== "undefined" ? window.location.origin : "";
  const iframe = document.createElement("iframe");
  iframe.setAttribute("aria-hidden", "true");
  iframe.style.cssText =
    "position:fixed;right:0;bottom:0;width:0;height:0;border:none;visibility:hidden;";
  document.body.appendChild(iframe);

  const win = iframe.contentWindow;
  const doc = iframe.contentDocument ?? win?.document;
  if (!doc || !win) {
    iframe.remove();
    options?.onDone?.();
    alert("Could not open print view.");
    return;
  }

  const cleanup = () => {
    window.setTimeout(() => iframe.remove(), 500);
    options?.onDone?.();
  };

  doc.open();
  doc.write(`<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)}</title>
  <style>
    ${PRINT_STYLES}
    h2 { page-break-after: avoid; }
    table { page-break-inside: auto; }
    tr { page-break-inside: avoid; }
    thead { display: table-header-group; }
  </style>
</head>
<body>
  <div class="report-header">
    <img src="${origin}/images/report-header.png" alt="AfriYAN Rwanda" />
  </div>
  ${bodyHtml}
  <div class="footer">Generated by Health Workforce Optimizer · ${new Date().toLocaleString()}</div>
</body>
</html>`);
  doc.close();

  const startPrint = () => {
    window.setTimeout(() => {
      try {
        win.focus();
        win.print();
      } finally {
        cleanup();
      }
    }, 250);
  };

  const img = doc.querySelector("img");
  if (!img || img.complete) {
    startPrint();
  } else {
    img.onload = startPrint;
    img.onerror = startPrint;
  }
}
